#!/usr/bin/env python2
# written by Moses Arocha
# The code requires the full installation of several programs and integrates the terminal.
## ROOT IS REQUIRED ##
import optparse
import socket
import os
import sys


def ProgramInstaller():
	os.system("sudo apt-get install nmap && sudo apt-get install xprobe2 && sudo apt-get install tshark")
	
def FinPortScanner(TargetHost):
	OSD = os.system("sudo nmap -sF "+TargetHost+" >> NetworkScan.txt")

def ACKScan(TargetHost):
	OSD = os.system("sudo nmap -sA "+TargetHost+" >> NetworkScan.txt")

def FragmentedIP(TargetHost):
	OSD = os.system("sudo nmap -ff "+TargetHost+" >> NetworkScan.txt")
	
def OSScanner(TargetHost):
	OSD = os.system("sudo xprobe2 "+TargetHost+" >> NetworkScan.txt")
	
def MacSpoof(TargetHost):
	OSD = os.system("sudo nmap -spoof-mac Cisco "+TargetHost+" >> NetworkScan.txt")

def WebServer(TargetHost):
	OSD = os.system("sudo nmap -sV -script=http-enum" +TargetHost+" >> NetworkScan.txt")

def SambaServer(TargetHost):
	OSD = os.system(" sudo nmap –script=samba-vuln-cve-2012-1182 -p139 "+TargetHost+" >> NetworkScan.txt")

def SMTPServer(TargetHost):
	OSD = os.system("sudo nmap -sV –script=smtp-strangeport "+TargetHost+ " >> NetworkScan.txt")

def PHPVersion(TargetHost):
	OSD = os.system("sudo nmap -sV –script=http-php-version "+TargetHost+" >> NetworkScan.txt")

def DNSBlackList(TargetHost):
	OSD = os.system("sudo nmap -sn "+TargetHost+" -script dns-blacklist >> NetworkScan.txt")

def HostPing(TargetHost):
	OSD = os.system("sudo nmap -sn "+TargetHost+" >> NetworkScan.txt")

def PortScan(TargetHost,TargetPort):
	OSD = os.system("sudo nmap -p "+TargetPort+" -sV -sS -T4 "+TargetHost+" >> NetworkScan.txt")	
	
def Options():
	print "nmap -sV -p 139,445 -oG grep-output.txt 10.0.1.0/24"
	print "nmap -sS -sV -T5 10.0.1.99 --webxml -oX - | xsltproc --output file.html -"

def NetBios(TargetHost):
	OSD = os.system("sudo nmap -sV -p 139,445 "+TargetHost+" >> NetworkScan.txt")
	User = raw_input(" Do You Want To Continue? [Y/N] ")
	if User == "Y" or User == "y":
		display = os.system("sudo nmap -sU --script nbstat.nse -p 137 "+TargetHost+" >> NetworkScan.txt")
		continuation = os.system("sudo nmap --script-args=unsafe=1 --script smb-check-vulns.nse -p 445 "+TargetHost+" >> NetworkScan.txt")
	else:
		print " Information has been outputed to a textfile."

def CheckHTTPServer(TargetHost):
	OSD = os.system("sudo nmap -p80,443 "+TargetHost+" -oG >> NetworkScan.txt")

def UDPScan(TargetHost,TargetPort):
	OSD = os.system("sudo nmap -p"+TargetPort+" "+TargetHost+" >> NetworkScan.txt")
	
def SCTPScan(TargetHost):
	OSD = os.system("sudo nmap -sY "+TargetHost+" >> NetworkScan.txt")

def AdvSCTPScan(TargetHost):
	OSD = os.system("sudo nmap -sZ "+TargetHost+" >> NetworkScan.txt")

def ZombieAttack(TargetHost,TargetPort):
	mask = raw_input(" What IP Do You Want To Mask Yourself As? ")
	OSD = os.system("sudo nmap -Pn -p"+TargetPort+" -sI "+mask+" "+TargetHost+" >> NetworkScan.txt")

def SpoofAddress(TargetHost):
	OSD = os.system("sudo nmap -S "+TargetHost+" >> NetworkScan.txt") 

def main():
	extensions = optparse.OptionParser('usage%prog -H <Target Host> -P <Target Port>')
	extensions.add_option('-H', '--Host', dest='TargetHost', type='string', help='specify target host')
	extensions.add_option('-P', '--Port', dest='TargetPort', type='string', help='specify target port')
	(options, args) = extensions.parse_args()
	TargetHost = options.TargetHost
	TargetPorts = str(options.TargetPort).split(',')
	if (TargetHost == None) | (TargetPorts[0] == None):
		print extensions.usage
		exit(0)
	f = open('NetworkScan.txt', 'w')
	ProgramInstaller()
	FinPortScanner()
	for TargetPort in TargetPorts:
		OSScanner(TargetHost)

if __name__ == '__main__':
	main()
