#!/usr/bin/env python2
# written by Moses Arocha

import optparse
import socket
import os
import argparse
import pickle

def ProgramInstaller():
	os.system("sudo apt-get install nmap && sudo apt-get install xprobe2 && sudo apt-get install tshark")
	
def FinPortScanner(TargetHost):
	OSD = os.system("sudo nmap -sF "+TargetHost+" >> NetworkScan.txt")

def ACKScan(TargetHost):
	OSD = os.system("sudo nmap -sA "+TargetHost+" >> NetworkScan.txt")

def FragmentedIP(TargetHost):
	OSD = os.system("sudo nmap -ff "+TargetHost+" >> NetworkScan.txt")
	
def OSScanner(TargetHost):
	OSD = os.system("sudo xprobe2 "+TargetHost+" >> NetworkScan.txt")
	
def MacSpoof(TargetHost):
	OSD = os.system("sudo nmap -spoof-mac Cisco "+TargetHost+" >> NetworkScan.txt")

def WebServer(TargetHost):
	OSD = os.system("sudo nmap -sV -script=http-enum" +TargetHost+" >> NetworkScan.txt")

def SambaServer(TargetHost):
	OSD = os.system(" sudo nmap –script=samba-vuln-cve-2012-1182 -p 139 "+TargetHost+" >> NetworkScan.txt")

def SMTPServer(TargetHost):
	OSD = os.system("sudo nmap -sV –script=smtp-strangeport "+TargetHost+ " >> NetworkScan.txt")

def PHPVersion(TargetHost):
	OSD = os.system("sudo nmap -sV –script=http-php-version "+TargetHost+" >> NetworkScan.txt")

def DNSBlackList(TargetHost):
	OSD = os.system("sudo nmap -sn "+TargetHost+" -script dns-blacklist >> NetworkScan.txt")

def main():
	extensions = optparse.OptionParser('usage%prog -H <Target Host> -P <Target Port>')
	extensions.add_option('-H', '--Host', dest='TargetHost', type='string', help='specify target host')
	extensions.add_option('-P', '--Port', dest='TargetPort', type='string', help='specify target port')
	(options, args) = extensions.parse_args()
	TargetHost = options.TargetHost
	TargetPorts = str(options.TargetPort).split(',')
	if (TargetHost == None) | (TargetPorts[0] == None):
		print extensions.usage
		exit(0)
	f = open('NetworkScan.txt', 'w')
	ProgramInstaller()
	FinPortScanner()
	for TargetPort in TargetPorts:
		OSScanner(TargetHost)

if __name__ == '__main__':
	main()
