#!/usr/bin/env python2
#Author is Moses Arocha
# Created in Python, created with the help of TJ O'Connor "Violent Python"

import dpkt
import socket
import pygeoip
import optparse

gi = pygeoip.GeoIP('/opt/GeoIP/Geo.dat')

def retGeoStr(ip):
   try:
	rec = gi.record_by_name(ip)
	city =  rec['city']
	if city != '':
	   geoLoc = city + ', ' + country
	else:
	   geoLoc = country
	return geoLoc
   except Exception, e:
	return 'Unregistered'

def printPcap(pcap):
   for (ts, buf) in pcap:
       try:
	   eth = dpkt.ethernet.Ethernet(buf)
	   ip = eth.data
	   src = socket.inet_ntoa(ip.src)
	   dst = socket.inet_ntoa(ip.dst)
	   print '[+] Src: ' + src + '--> Dst: ' + dst
	   print '[+] Src: ' + retGeoStr(src) + '--> Dst: ' + retGeoStr(dst)
       except:
	   pass


def main():
   parser = optparse.OptionParser('usage%prog -p <pcap file>')
   parser.add_option('-p', dest='pcapFile', type='string', help='specify pcap filename')
   (options, args) = parser.parse_args()
   if options.pcapFile == None:
	print parser.usage
	exit(0)
   pcapFile = options.pcapFile
   f = open(pcapFile)
   pcap = dpkt.pcap.Reader(f)	# where the problem lays
   printPcap(pcap)

if __name__ == '__main__':
	main()
