#!/usr/bin/env python2
#Author is Moses Arocha
# Created in Python, created with the help of TJ O'Connor "Violent Python"

import dpkt
import socket
import pygeoip
import optparse

gi = pygeoip.GeoIP('/opt/GeoIP/Geo.dat')

def retGeoStr(ip):
   try:	
	rec = gi.record_by_name(ip)
	city = rec['city']
	country = rec['country_code3']
	if city !='':
	   geoLoc = city + ', ' + country
	else:
	   geoLoc = country
	return geoLoc
   except Exception, e:
	return 'Unregistered'

def printTxtFile():
	f = open('myfile.txt', 'w')	   
	for (x) in range(1, 1000):
		eth = dpkt.ethernet.Ethernet(buf)
		ip = eth.data
		src = socket.inet_ntoa(ip.src)
		dst = socket.inet_ntoa(ip.dst)
		f.write('[+] Src : ' + src + '--> Dst: ' + dst)
		f.write('[+] Src : ' + retGeoStr(src) + '--> Dst: ' + retGeoStr(dst))
		
	f.close()

def main():
	parser = optparse.OptionParser('usage%prog -p <text file>')
	parser.add_option('-p', dest='txtFile', type='string', help='specify text filename')
	(options,args) = parser.parse_args()
	if options.txtFile == None:
		print parser.usage
		exit(0)
	txtFile = options.txtFile
	printTxtFile()
	
if __name__ == '__main__':
	main()
