#!/usr/bin/env python2
# written by Moses Arocha

import nmap
import optparse

def PortScan(TargetHost, TargetPort):
	nmScan = nmap.PortScanner()
	nmScan.scan(TargetHost, TargetPort)
	state = nmScan[TargetHost]['tcp'][int(TargetPort)]['state']
	print "\n [Results] " + TargetHost + " TCP Port/" +TargetPort + " " + state

def main():
	parser = optparse.OptionParser('usage%prog -H <Target Host> -P <Target Port>')
	parser.add_option('-H', '--Host', dest='TargetHost', type='string', help='specify target host')
	parser.add_option('-P', '--Port',  dest='TargetPort', type='string', help='specify targe port')
	(options, args) = parser.parse_args()
	TargetHost = options.TargetHost
	TargetPorts = str(options.TargetPort).split(',')
	if (TargetHost == None) | (TargetPorts[0] == None):
		print parser.usage
		exit(0)
	for TargetPort in TargetPorts:
		PortScan(TargetHost, TargetPort)

if __name__ == '__main__':
	main()
